# Generated by Django 3.2.9 on 2021-12-07 13:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_seller_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('closing_time', models.DateTimeField(default=datetime.datetime(2021, 12, 14, 13, 54, 18, 410207))),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.seller')),
            ],
        ),
    ]
